# Generated by Django 5.1.2 on 2024-10-27 23:36

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('store', '0009_alter_cartitem_quantity'),
	]

	operations = [
		migrations.AlterField(
			model_name='cart',
			name='id',
			field=models.CharField(
				default=uuid.uuid4,
				editable=False,
				max_length=36,
				primary_key=True,
				serialize=False,
			),
		),
	]
