version: '3'

services:
  postgres:
    image: postgres:14.2
    ports:
      - 5435:5432
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: storefront
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - 5051:5051
    environment:
      PGADMIN_DEFAULT_EMAIL: local@local.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin