name: Test

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]
    types:
      - opened
      - reopened
      - synchronize

jobs:
  Test:
    runs-on: ubuntu-latest
    container: python:3.13.1-slim-bullseye
    services:
      postgres:
        image: postgres:14.2
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: storefront
        # NOTE: Sets health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # - name: Setup python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.13'
      - name: Install dependencies
        # NOTE: We use the --system flag so packages are installed into the system python and not into a virtualenv
        run: |
          pip install --upgrade pip 
          pip install pipenv
          pipenv install --system --dev
      - name: Verify linter
        uses: astral-sh/ruff-action@v3
      - name: Run tests     
        run: pytest